---
title: "Bird Joins"
author: "Elise Gonzales"
date: "2022-08-16"
output: html_document
---
##Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(datapasta)
library(janitor)
library(lubridate)
```

##Read in data
```{r}
bird_observations <- read_csv(here("data", "52_pp52_birds_1.csv"))
  
sites <- read_csv(here("data", "52_pp52_sites_1.csv"))
  
surveys <- read_csv(here("data", "52_pp52_surveys_1.csv"))
  
taxalist <- read_csv(here("data", "52_pp52_taxalist_1.csv"))
```
###Task 1
##Create subset
```{r}
birds_subset <- bird_observations |> 
  filter(species_id %in% c("BHCO", "RWBL"), site_id %in% c("LI-W", "NU-C"))
```

##Left-join
```{r}
birds_left <- left_join(birds_subset, sites, by = "site_id") |> 
  left_join(taxalist, by = "species_id")
```

##Full-join
```{r}
birds_full <- full_join(birds_subset, sites, by = "site_id")
```

##Inner-join
```{r}
birds_inner <- inner_join(birds_subset, taxalist, by = "species_id")

birds_left_join <- left_join(birds_subset, taxalist, by = "species_id")
```

###Task 2
##Clean, vis
```{r}
bird_observations <- bird_observations |> 
  rename(bird_obs_notes = notes)
```

##subset
```{r}
task2_subset <- left_join(bird_observations, taxalist, by = "species_id") |> 
  left_join(sites, by = "site_id") |> 
  left_join(surveys, by = c("site_id", "survey_id")) |> 
  select(survey_date, common_name, park_name, bird_count) |> 
  mutate(survey_month = lubridate::month(survey_date)) |> 
  mutate(survey_month = as.factor(survey_month)) |> 
  relocate(survey_month, .after = survey_date)
#make sure to explicitly say which variables to check for. Use vector if multiple. 
```

```{r}
group_task2 <- task2_subset |> 
  group_by(park_name, survey_month) |> 
  summarize(birds_tot = n()) |> 
  filter(park_name %in% c("Lindo", "Orme", "Palomino", "Sonrisa"))
```


